FROM oven/bun:1

ENV DATABASE_URL="file:./db.sqlite"

# Next Auth Discord Provider
ENV DISCORD_CLIENT_ID=""
ENV DISCORD_CLIENT_SECRET=""
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=""
ENV CLERK_SECRET_KEY=""

ENV NEXT_PUBLIC_CLERK_SIGN_IN_URL=""
ENV NEXT_PUBLIC_CLERK_SIGN_UP_URL=""


WORKDIR /app
COPY . .

RUN bun i
RUN bun run build

CMD ["bun", "run", "start"]